### ISSUE TITLE
Blackscreen when running the Demo 

### ISSUE THREAD

**Issue by Adlerkampf** [ViperCharts/viper-charts-js#9]
I just cloned the repository and ran 

`npm i`
 `npm run start`

Weirdly, I just see a black website. I'm using a Windows computer and chrome with JavaScript enabled

**Comment by TrystonPerry** [comment]
Thanks for posting an issue! I've gone ahead and fixed this in master. There's also a demo available at https://viper-charts.netlify.app/ that you can play with if you don't want to run locally. 

The reason this was happening was because the demo code was hardcoded to work specifically with Viper Pro (our premium product). So requests were blocked from unauthenticated users.

The demo now uses the public Binance Spot API.
